# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ethtx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ethtx
  pod "HockeySDK"

end

target 'ethtx-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ethtx-tvOS

  target 'ethtx-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
